### PR TITLE
Dust off the docs

### PR DESCRIPTION
**Pull request by mmlb**
## Description

Quite the ~spring~winter cleaning to the docs site.

I've done a bunch of mostly cosmetic fixes + fix links + removed some slightly different terms for the same thing.
I've also ensured all the triple-backticks-code-blocks have a language specified that is known to both github and pygments so that we get better syntax highlighting and grepability (for the ` ```text` case, we at least get to see the opening/closing fences easily).

There's a bunch of stuff going on here please see the individual commits + messages for what/why.

## Why is this needed

This site is/was in need of lots of love. Links were broken, content is out of date. This is my first stab at giving some love.

Fixes: #42 

## How Has This Been Tested?

I've added CI for both smart quotes and dead links, see https://github.com/mmlb/tinkerbell-tinkerbell-docs/actions?query=branch%3Adust-off-docs

I've also compared live site vs the preview visually using [diffsite](https://pianomister.github.io/diffsite/?url1=https%3A%2F%2Fdocs.tinkerbell.org&url2=https%3A%2F%2Fdeploy-preview-138--tinkerbell-docs.netlify.app%2F).

## How are existing users impacted? What migration steps/scripts do we need?

Better documentation site *today*, easier to improve for tomorrow.

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [x] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by mmlb** [comment]
Ok I think this is ready for review and merging. I've compared the before and after sites using https://pianomister.github.io/diffsite/?url1=https%3A%2F%2Fdocs.tinkerbell.org&url2=https%3A%2F%2Fdeploy-preview-138--tinkerbell-docs.netlify.app%2F and the differences are expected/on-purpose.

**Comment by mmlb** [comment]
For those comparing the live vs preview site, they font and other css looks different because we're pulling in a css file that is gated from the referrer which is not matching against the preview site and thus we end up with fallback fonts/css.

**Review by DailyAlice — APPROVED** [review]
I took a look mostly at the overall structural changes and all the markdown, formatting, functionality checks out to me. (At least, it doesn't seem to introduce any new bugs.) I didn't do a full read-through or proofread pass, but that might be better suited to its own PR after publishing this one, if we want to do one.

**Comment by mmlb** [comment]
> I took a look mostly at the overall structural changes and all the markdown, formatting, functionality checks out to me. (At least, it doesn't seem to introduce any new bugs.) 

Thanks!

> I didn't do a full read-through or proofread pass, but that might be better suited to its own PR after publishing this one, if we want to do one.

There's a lot wrong / out of date right now anyway and I'll be doing some smaller PRs for the content updates soon.

**Pull request merged**
