### PR TITLE
Bootstrap contributor section

### PR DESCRIPTION
**Pull request by gianarb**
This commit bootstrap the contributors section of the documentation

Signed-off-by: Gianluca Arbezzano <gianarb92@gmail.com>

### CODE REVIEW

**Comment by DailyAlice** [comment]
I like it! Or well, the idea of it. I haven't gotten around to reading through it. But I did want to say that I think it's probably helpful to get targeted developer specific content out there.

**Comment by gianarb** [comment]
Thanks!

> it's probably helpful to get targeted developer specific content out
there.

Do you mind elaborating a little bit? Because I don't understand what you
mean.

**Comment by DailyAlice** [comment]
yes! I guess in this context it's better phrased as "targeted, contributor-specific content" as compared to the other sections of the docs, which are more developer-user focused.

I don't know if that distinction will always be helpful for our docs and community, but it seems good for now.

**Comment by gianarb** [comment]
Yeah, that's why I created a new item in the menu and I placed all of the pages in there. I am not sure how we can improve the doc to separate the contributor land from the userland even more.

**Review by DailyAlice — APPROVED** [review]
Looks pretty good to me. Gonna go ahead and publish and then do a run through of grammar and formatting things after.

**Pull request merged**
