### PR TITLE
Operating system docs

### PR DESCRIPTION
**Pull request by thebsdbox**
## Description

This adds documentation around Operating Systems and provisioning the,

## Why is this needed

It currently is missing documentation

Fixes: #

## Checklist:

I have:

- [x] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by stolsma** [comment]
Nice text!👍

**Comment by DailyAlice** [comment]
Thinking about content org - you are planning more docs for this "Deploying Operating Systems" section, yes?

**Review by DailyAlice — APPROVED** [review]
LGTM! I will follow-up with a PR to add the doc to the table of contents.

**Comment by stolsma** [comment]
@DailyAlice This pr is merged without updating the mentioned wrong url reference.... Can you resolve that problem or shall I make a new pr?

**Pull request merged**
