### PR TITLE
Add/update DCO, CoC, contributing ... files

### PR DESCRIPTION
**Pull request by mmlb**
## Description

Update non code files to be uniformish amongst all repos.

## Why is this needed

Ensures our repos are all licensed correctly and contain similar/minimum
contribution info files.

### CODE REVIEW

**Comment by DailyAlice** [comment]
Quick Question - is the DCO doc intended to be published at docs.tinkerbell.org?

If it is, we'll need to find a place for it in the TOC (mkdocs.yml). If it isn't, it should probably just live in the top-level directory with all the other meta, yes?

**Comment by mmlb** [comment]
> Quick Question - is the DCO doc intended to be published at docs.tinkerbell.org?
> If it is, we'll need to find a place for it in the TOC (mkdocs.yml).

Hmm yes we *should* probably have it in docs somewhere, but I think more than just a link from the TOC, like a small explainer page that then links to DCO.md for the actual dco content.

> If it isn't, it should probably just live in the top-level directory with all the other meta, yes?

So this is following the layout I've done in all the other repos (https://github.com/orgs/tinkerbell/projects/7) and I'd like to keep them all the same. I'd be ok with some other top-level dir instead of `docs` if you'd like to keep them separate. This DCO is a meta-file for the repo itself, but can/should also serve as content for the site too.

**Comment by mmlb** [comment]
@DailyAlice I forgot to tag you in my response ^.

**Comment by DailyAlice** [comment]
Yeah, the `docs` folder in the documentation repo is specifically for the markdown source that is published on the site. I think if it's meta, it should just live in the top-level. So if it's content about the repo and not published it should live not in the `docs` folder.

I'm still leaning towards putting it along side all the other meta-repo things like the license file.

Thanks for the context!

**Comment by mmlb** [comment]
> Yeah, the `docs` folder in the documentation repo is specifically for the markdown source that is published on the site. I think if it's meta, it should just live in the top-level. So if it's content about the repo and not published it should live not in the `docs` folder.
> 
> I'm still leaning towards putting it along side all the other meta-repo things like the license file.

Well it can/should be both meta and content :D, and I'd love to keep it in sync with all the other repos so we can be able to do mass changes with minimal effort if necessary.

**Pull request merged**
