### PR TITLE
Update /setup/packet-terraform references to /setup/equinix-metal-terraform

### PR DESCRIPTION
**Pull request by tstromberg**
Fixes bug noticed on https://docs.tinkerbell.org

Related issue: #42

### CODE REVIEW

**Review by markyjackson-taulia — APPROVED** [review]
Thank you for this PR

**Comment by tstromberg** [comment]
Can has approval?

**Comment by markyjackson-taulia** [comment]
> Can has approval?

On it. Sorry for the delay

**Review by gianarb — APPROVED** [review]
Thanks a lot!!

**Pull request merged**
