### PR TITLE
Split tink worker, cli, server in its own page

### PR DESCRIPTION
**Pull request by gianarb**
I think they all deserve their own page. It simplifies about ability to
reference the documentation for a specific service in other pages as
well.

Signed-off-by: Gianluca Arbezzano <gianarb92@gmail.com>

### CODE REVIEW

**Comment by mmlb** [comment]
@gianarb Did you forget to `git add` 2 files?

**Comment by gianarb** [comment]
How did you know that?! :) yes! But now I have fixed it! Thanks

>

**Comment by mmlb** [comment]
:ear: :bird:

**Comment by DailyAlice** [comment]
For the "Next Steps" sections, are those sections highlighting where development is currently happening? If so, I'm thinking that maybe making a different sub-heading, like "Future Development", or "Upcoming Features", or "On-going Work"

When I read "Next Steps" in docs, I typically interpret it as next steps for the user to take after they have ingested what is on the page.

**Review by DailyAlice — APPROVED** [review]
lgtm!

**Pull request merged**
