### PR TITLE
Examples for Ubuntu/Debian

### PR DESCRIPTION
**Pull request by thebsdbox**
## Description

Adds a bunch of documentation about creating workflows for Debian and Ubuntu

## Why is this needed

Documentation is lacking

Fixes: #

## Checklist:

I have:

- [x] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by gianarb** [comment]
Awesome... I only have one concern, should we remove this? https://github.com/tinkerbell/workflows/tree/master/ubuntu_18_04 or how should we explain the fact that we have workflows in two places?

**Comment by thebsdbox** [comment]
> Awesome... I only have one concern, should we remove this? https://github.com/tinkerbell/workflows/tree/master/ubuntu_18_04 or how should we explain the fact that we have workflows in two places?

I'd suggest we leave that in place for now.. until these docs reach a critical mass then we can revisit distributing this stuff.

**Comment by gianarb** [comment]
Sounds great!

**Comment by DailyAlice** [comment]
> Sounds great! We have an Example section already with a Hello World workflow. any idea about that? Just trying to figure out how we can avoid the community getting lost in the various place we have "things"

Hmm...looking at the docs, I think these look good in the Operating Systems section, but there is the [Examples](https://tinkerbell.org/examples/) section of the website. 

Perhaps we add the links there as well once these are published?

**Comment by gianarb** [comment]
Or we can rename Example to "Workflows" leaving only everything in one
place. In the end those are all workflows (even the Example/Hello World is
a workflow). Or we can remove Example because with this new work Dan is
doing we probably don't need it anymore

**Review by DailyAlice — APPROVED** [review]
approving and merging, there does need to be a little formatting clean-up that I will include in a follow-up PR.

**Pull request merged**
